[[redirects]]
    from = "/plausible/js/script.js"
    to = "https://plausible.io/js/pa-6yZEoYxvJYS8CmxAsGEem.js"
    status = 200

[[redirects]]
    from = "/plausible/api/event"
    to = "https://plausible.io/api/event"
    status = 200